cc_library(
    name = "singly",
    srcs = glob(["src/*.c"]),
    hdrs = glob(["include/*.h"]),
    includes = ["include"],
    visibility = [
        "//main:__pkg__",
        "//dsa/stack:__pkg__",
    ],
)
