cc_library(
    name = "stack",
    srcs = ["src/stack.c"],
    hdrs = ["include/stack.h"],
    includes = ["include"],
    deps = ["//dsa/linked-list/singly"],
    visibility = ["//main:__pkg__"],
)
